# Generated by Django 6.0.2 on 2026-02-23 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("Cart", "Karta"),
                            ("Cash", "Naqd Pul"),
                            ("Click", "Click Orqali"),
                            ("Payme", "Payme Orqali"),
                            ("Coin", "Tagada"),
                        ],
                        default="Cash",
                        max_length=50,
                    ),
                ),
                (
                    "student_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.course",
                    ),
                ),
            ],
        ),
    ]
